import type { Metadata } from "next";
import './globals.css'
import { Providers } from "./providers";
import { LayoutManager } from "./LayoutManager"; 

export const metadata: Metadata = {
  title: "Selaras",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <LayoutManager>{children}</LayoutManager>
        </Providers>
      </body>
    </html>
  );
}
